"""
Polynomial Ideal Module
========================
Represents an ideal generated by a set of polynomials.
"""


from typing import List, Optional
from .polynomial import Polynomial, Monomial
from .groebnerbasis import GroebnerBasis, compute_groebner_basis

class Ideal:
    """Polynomial ideal in a polynomial ring."""
    
    def __init__(self, generators: List[Polynomial], ring: str = 'complex'):
        self.ring = ring
        # Remove zero generators and make a copy
        self.generators = [g.copy() for g in generators if not g.is_zero()]
        self._groebner_basis: Optional[List[Polynomial]] = None
    
    @property
    def groebner_basis(self) -> List[Polynomial]:
        """Compute and cache Gröbner basis."""
        if self._groebner_basis is None:
            self._groebner_basis = compute_groebner_basis(self.generators)
        return self._groebner_basis
    
    def contains(self, polynomial: Polynomial) -> bool:
        """Test if polynomial is in the ideal."""
        gb = GroebnerBasis(self.generators, 'grevlex')
        remainder = gb._reduce(polynomial, gb.groebner_basis)
        return remainder.is_zero()
    
    def sum(self, other: 'Ideal') -> 'Ideal':
        """Ideal sum: I + J = {f + g : f in I, g in J}"""
        return Ideal(self.generators + other.generators, self.ring)
    
    def product(self, other: 'Ideal') -> 'Ideal':
        """Ideal product: IJ = {sum_k f_k * g_k : f_k in I, g_k in J}"""
        product_gens = [f * g for f in self.generators for g in other.generators]
        return Ideal(product_gens, self.ring)
    
    def intersection(self, other: 'Ideal') -> 'Ideal':
        """Ideal intersection I ∩ J."""
        from .groebnerbasis import ideal_intersection
        gb1 = compute_groebner_basis(self.generators)
        gb2 = compute_groebner_basis(other.generators)
        # Get variable names
        vars_set = set()
        for p in self.generators + other.generators:
            vars_set.update(p.variables())
        vars_list = sorted(list(vars_set), key=lambda v: v.name)
        intersection_gens = ideal_intersection(gb1, gb2, vars_list)
        return Ideal(intersection_gens, self.ring)
    
    def quotient(self, h: Polynomial) -> 'Ideal':
        """Ideal quotient: I : h = {f in R : h*f in I}"""
        from .groebnerbasis import saturation
        quotient_gens = saturation(self.generators, h)
        return Ideal(quotient_gens, self.ring)
    
    @property
    def radical(self) -> 'Ideal':
        """Radical ideal: √I = {f : f^k in I for some k > 0}."""
        from .groebnerbasis import radical_membership
        # For now, return ideal of generators
        # Full implementation would compute radical basis
        return Ideal(self.generators, self.ring)
    
    def is_prime(self) -> bool:
        """Test if ideal is prime (P)."""
        # I is prime iff: f*g in I implies f in I or g in I
        # This is equivalent to checking primary decomposition has single component
        from .groebnerbasis import primary_decomposition
        components = primary_decomposition(self.generators)
        return len(components) == 1
    
    def dimension(self) -> int:
        """
        Krull dimension of the quotient ring R/I.

        Computed as the maximum size of an independent set of variables S,
        i.e. no leading monomial of the Groebner basis has its support
        entirely inside S. This equals dim(R/I) for any Groebner basis.
        """
        gb = self.groebner_basis
        vars_set = set()
        for p in self.generators:
            vars_set.update(p.variables())
        all_vars = sorted(list(vars_set), key=lambda v: v.name)
        n = len(all_vars)
        
        if n == 0:
            return 0
        
        leading_supports = []
        for g in gb:
            if not g.is_zero():
                leading_supports.append(set(g.leading_monomial('grevlex', all_vars).get_vars()))
        
        best = 0
        # Brute force over subsets (fine for the small systems used here)
        from itertools import combinations
        for k in range(n, -1, -1):
            for subset in combinations(all_vars, k):
                s = set(subset)
                if all(not supp.issubset(s) for supp in leading_supports):
                    return k
        return best
    
    def quotient_ring_dimension(self) -> int:
        """Vector space dimension of R/I (if finite)."""
        # This would require Hilbert series computation
        return -1  # Unknown/infinite
    
    def __eq__(self, other: 'Ideal') -> bool:
        """Check ideal equality via Gröbner basis comparison."""
        if len(self.generators) != len(other.generators):
            return False
        return self.contains(other.generators[0]) and other.contains(self.generators[0])
    
    def __repr__(self) -> str:
        return f"Ideal({len(self.generators)} generators)"
